env:
    credentials: "ENCRYPTED[!20416f5e1a8c05a6f76cbc8a49f6d407ebbb375dba5ab0c4a3e47e43891c268f975cf88fe398e0bf9e92312a4bd4b6fb!]"
    rcloneconfig: "ENCRYPTED[!8761b98f4dc2f96e915c564fb3eb56cc9461e10e89ef9e410d2c9f7b3949f9fab647b12d2c94324c391ef83f74467483!]"
    tokentl: "ENCRYPTED[!deddb3f79fbea3f788d614602eef7af66c5bfa0897318de20652f4c51737308b8c9e594424e5160d7d6c34a951310064!]"
    idtl: "ENCRYPTED[!323ab361d49c6fec45d5a17dfb4616fa7679cc0c089ed65d8f538d5769e7155462e05fdd585615c774774daf7700c853!]"
    lunch: lunch qassa_ysl-userdebug
    make: make qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "ALprjkt"
       - git config --global user.email "ALprjkt168145100+ALprjkt@users.noreply.github.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy rom:rom/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Qassa Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q -g default,-mips,-darwin,-notdefault
      - git clone --depth 1 https://github.com/ALprjkt/local_manifest.git -b qassa .repo/local_manifests
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
#      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="ALprjkt"
      - export BUILD_HOSTNAME="Cirrus"
      - export KBUILD_BUILD_USER="ALprjkt"
      - export KBUILD_BUILD_HOST="Cirrus"
 #     - export WITH_GAPPS=true
      - export ALLOW_MISSING_DEPENDENCIES=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Qassa for ysl Start!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/ysl/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz rom:rom -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"
